name: Semantic Breaking Change PR Test

# FIXME: this is test logic
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

  workflow_dispatch:

jobs:
  main:
    name: Validate Breaking Change PR Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/breaking-pr-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
