name: Semantic Breaking Change PR 2

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  main:
    name: Validate Breaking Change PR 2
    runs-on: ubuntu-latest
    cache: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/breaking-pr-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
